### ISSUE TITLE
roslaunch gcamp_gazebo gazebo_world.launch 입력시 Error 발생

### ISSUE THREAD

**Issue by shining-sakaeru** [Road-Balance/gcamp_ros_basic#4]
https://www.youtube.com/watch?v=MDz1t70gW3U&list=PLK2UKp8KOXe04i19yvCRllFTAXfmnCMnE&index=3
보고 문의드립니다.
SpotMicro와 병행해서 덕분에 잘 보고 배우고 있습니다 =)

Environment
- WSL 2 : xrdp 접속 (강의해주신대로 WSL로 하니 에러가 엄청뜨네요.. 구글링 통해서 어렵게 여기까지 왔습니다)
- Ubuntu 18.04.5 LTS

Guide 대로 진행을 했는데 아래처럼 이미지가 뜨네요..
![image](https://user-images.githubusercontent.com/58348302/114288427-ddb9ef00-9aaa-11eb-8398-a335ae9ae847.png)

gui.ini 설정은 해뒀고, 
![image](https://user-images.githubusercontent.com/58348302/114288480-3f7a5900-9aab-11eb-9e5b-642c34d50dcc.png)

 ~/.models 폴더 안에 gazebo_world 폴더가 있어야하는데 없어서 그런게 아닐까 추측해봅니다
![image](https://user-images.githubusercontent.com/58348302/114288512-8cf6c600-9aab-11eb-8cfb-0718d1869062.png)

참고로 Gazebo를 별도 실행했을 때에는 잘 켜지기에 Gazebo 실행환경에는 문제가 없는듯합니다.
![image](https://user-images.githubusercontent.com/58348302/114288565-13aba300-9aac-11eb-9937-054c24e230ab.png)

**Comment by kimsooyoung** [comment]
안녕하세요 우선 피드백 감사합니다. 

강의와 다른 환경이어 제가 명확한 답을 드리기는 쉽지 않지만, 주신 사진자료로 보았을 때

`gcamp_ws`가 아닌 `spotmicro_ws`를 사용하고 계신 것으로 보입니다.

**Comment by shining-sakaeru** [comment]
안녕하세요 말씀하신대로 spotmicro_ws 로 (사실 spotmicro랑 헷갈려서 이름을 잘못 지었습니다만 ㅎㅎ..)
하다가 강의 내용과 완전 동일하게 gcamp_ws이름으로 workspace를 다시 만들어서 진행했습니다.

현재 켜지고 있어 issue 해결이 되었습니다. ... 노트북밖에 없어서 진행중인데
model 불러오는데만 5분 좀 안되게 걸렸네요

Windows + WSL 관련해서는 notion에 정리중인데 시도해 본  history가 엉켜있어
정리는 되어있지 않습니다. 필요하시면 notion link로 공유드리겠습니다. (email : sakaeru@korea.ac.kr)

**Comment by kimsooyoung** [comment]
피드백 감사합니다.

첫 실행은 오래 걸리지만 그 이후론 빠르게 되실 것입니다. 👍

이메일 통해 노션과 연동된 이메일도 공유드립니다.

기회가 된다면 `sakaeru`님과 함께 Windows 개발환경 강의도 진행해보고 싶습니다. 😁😁

**Comment by shining-sakaeru** [comment]
이메일로 notion link및 invite 내용 회신드렸습니다.
함께 하는것은 기회되면 같이 해요 =)
한참 공부중이지만 지금부터 함께해도 상관없습니다
