### ISSUE TITLE
Have no access to BOM list

### ISSUE THREAD

**Issue by shining-sakaeru** [Road-Balance/gcamp_ros_basic#5]
16강에 BOM 목록을 보고 싶은데 열람 권한이 없네요...
Access 요청을 하긴 했는데, 혹시 강사님이 주시는거라면 승인 부탁드리고
혹여 따로 가지고 계신게 있다면 attachment로 공유 부탁드립니다.

![image](https://user-images.githubusercontent.com/58348302/114295823-92233780-9ae2-11eb-908d-baef4783e15f.png)

**Comment by kimsooyoung** [comment]
피드백에 감사합니다.

링크 권한 변경 완료하였습니다. 

메일을 확인하시거나, 하단의 링크를 클릭하시면 됩니다.

https://docs.google.com/spreadsheets/d/17zowCNSFzXSP93aSqZCBOPqbYnzJNzqa4P7oqEBqimE/edit?usp=sharing

확인 후 완료 여부를 공유 부탁드립니다.

**Comment by shining-sakaeru** [comment]
잘 열리는것 확인했습니다.
감사합니다 =)
