### ISSUE TITLE
Drive_forward 예제 문의

### ISSUE THREAD

**Issue by shining-sakaeru** [Road-Balance/gcamp_ros_basic#8]
6강 내용중 
Git clone이후 해주면 좋다. 고 
언급하고 지나가신 부분이있는데 (2:00)
간단하게라도 어떤 내용인지 설명부탁드립니다.
chmod 는 linux 권한추가 기능으로 알고있는데
어떤 결과를 위해 사용하는지 알려주시면 충분할듯합니다

(Origin.)
roscd topic_tutorial
cd src && chmod +x *
cd ../
cd launch && chmod +x *

**Comment by kimsooyoung** [comment]
![github_issue](https://user-images.githubusercontent.com/12381733/114389600-261efd00-9bd0-11eb-8373-fe1b3beb9b7c.png)

관련 내용 추가 완료하였습니다. 

감사합니다.

**Comment by shining-sakaeru** [comment]
감사합니다 =)
