### ISSUE TITLE
cmdvel_pub_endless.py error

### ISSUE THREAD

**Issue by shining-sakaeru** [Road-Balance/gcamp_ros_basic#9]
6강 영상 12:39 에 나오는데
gcamp_ws에서 rosrun 으로 py실행이 되는걸 볼수있는데
제 환경에서는 되지않고 직접해당폴더를 찾아들어가 실행할수 있었습니다.

강의 초반에 ~/models 까지  path를 환경변수 지정했는데, ~/.gazebo/gui.ini 에 환경변수를 추가로 지정해도 바로 실행이 되지않습니다

Error msg.
[rospack] Error: package ‘topic_tutorial’ not found

**Comment by kimsooyoung** [comment]
[해당 이슈](https://github.com/Road-Balance/gcamp_ros_basic/issues/9)와 관련된 내용으로 보입니다. 

수정한 강의 노트를 따라 다시 한 번 해보시겠어요? 
혹시 문제가 계속된다면, 커멘드 부탁드립니다.

감사합니다.

**Comment by shining-sakaeru** [comment]
해당 이슈 링크가 순환참조 된듯합니다.
강의노트는 보고있는데..

혹시 저도 초대 가능하실까요?
지금은 duplicate 해서 보는중이어서요 (.. )

**Comment by kimsooyoung** [comment]
링크 수정 완료하였습니다.

`sakaeru@korea.ac.kr`로 초대 넣었으며, comment 권한 풀어드렸습니다. 

매번 정말 감사합니다. :)

**Comment by shining-sakaeru** [comment]
배우고 있는 입장인걸요.. 제가 더 감사합니다 ☀

**Comment by shining-sakaeru** [comment]
rospack list 명령어로 찾아보니 해당 package가 없네요... ? ros_full 설치했는데..
6강 후반부처럼 package 생성하고, 원래 있던 파일들을 해당 package 폴더에 넣으면 해결될 듯하네요.
의견 부탁드립니다.

...package 폴더는 있는데 rospack 으로 안잡힌다는게 의문으로 남네요;

[rospack list]
actionlib /opt/ros/melodic/share/actionlib
actionlib_msgs /opt/ros/melodic/share/actionlib_msgs
actionlib_tutorials /opt/ros/melodic/share/actionlib_tutorials
angles /opt/ros/melodic/share/angles
bond /opt/ros/melodic/share/bond
bondcpp /opt/ros/melodic/share/bondcpp
bondpy /opt/ros/melodic/share/bondpy
camera_calibration /opt/ros/melodic/share/camera_calibration
camera_calibration_parsers /opt/ros/melodic/share/camera_calibration_parsers
camera_info_manager /opt/ros/melodic/share/camera_info_manager
catkin /opt/ros/melodic/share/catkin
class_loader /opt/ros/melodic/share/class_loader
cmake_modules /opt/ros/melodic/share/cmake_modules
compressed_depth_image_transport /opt/ros/melodic/share/compressed_depth_image_transport
compressed_image_transport /opt/ros/melodic/share/compressed_image_transport
control_msgs /opt/ros/melodic/share/control_msgs
control_toolbox /opt/ros/melodic/share/control_toolbox
controller_interface /opt/ros/melodic/share/controller_interface
controller_manager /opt/ros/melodic/share/controller_manager
controller_manager_msgs /opt/ros/melodic/share/controller_manager_msgs
costmap_2d /opt/ros/melodic/share/costmap_2d
cpp_common /opt/ros/melodic/share/cpp_common
cv_bridge /opt/ros/melodic/share/cv_bridge
depth_image_proc /opt/ros/melodic/share/depth_image_proc
diagnostic_aggregator /opt/ros/melodic/share/diagnostic_aggregator
diagnostic_analysis /opt/ros/melodic/share/diagnostic_analysis
diagnostic_common_diagnostics /opt/ros/melodic/share/diagnostic_common_diagnostics
diagnostic_msgs /opt/ros/melodic/share/diagnostic_msgs
diagnostic_updater /opt/ros/melodic/share/diagnostic_updater
diff_drive_controller /opt/ros/melodic/share/diff_drive_controller
dynamic_reconfigure /opt/ros/melodic/share/dynamic_reconfigure
eigen_conversions /opt/ros/melodic/share/eigen_conversions
filters /opt/ros/melodic/share/filters
find_object_2d /opt/ros/melodic/share/find_object_2d
forward_command_controller /opt/ros/melodic/share/forward_command_controller
gazebo_dev /opt/ros/melodic/share/gazebo_dev
gazebo_msgs /opt/ros/melodic/share/gazebo_msgs
gazebo_plugins /opt/ros/melodic/share/gazebo_plugins
gazebo_ros /opt/ros/melodic/share/gazebo_ros
gazebo_ros_control /opt/ros/melodic/share/gazebo_ros_control
gencpp /opt/ros/melodic/share/gencpp
geneus /opt/ros/melodic/share/geneus
genlisp /opt/ros/melodic/share/genlisp
genmsg /opt/ros/melodic/share/genmsg
gennodejs /opt/ros/melodic/share/gennodejs
genpy /opt/ros/melodic/share/genpy
geometry_msgs /opt/ros/melodic/share/geometry_msgs
gl_dependency /opt/ros/melodic/share/gl_dependency
hardware_interface /opt/ros/melodic/share/hardware_interface
image_geometry /opt/ros/melodic/share/image_geometry
image_proc /opt/ros/melodic/share/image_proc
image_publisher /opt/ros/melodic/share/image_publisher
image_rotate /opt/ros/melodic/share/image_rotate
image_transport /opt/ros/melodic/share/image_transport
image_view /opt/ros/melodic/share/image_view
interactive_marker_tutorials /opt/ros/melodic/share/interactive_marker_tutorials
interactive_markers /opt/ros/melodic/share/interactive_markers
joint_limits_interface /opt/ros/melodic/share/joint_limits_interface
joint_state_controller /opt/ros/melodic/share/joint_state_controller
joint_state_publisher /opt/ros/melodic/share/joint_state_publisher
kdl_conversions /opt/ros/melodic/share/kdl_conversions
kdl_parser /opt/ros/melodic/share/kdl_parser
kdl_parser_py /opt/ros/melodic/share/kdl_parser_py
laser_assembler /opt/ros/melodic/share/laser_assembler
laser_filters /opt/ros/melodic/share/laser_filters
laser_geometry /opt/ros/melodic/share/laser_geometry
libg2o /opt/ros/melodic/share/libg2o
librviz_tutorial /opt/ros/melodic/share/librviz_tutorial
map_msgs /opt/ros/melodic/share/map_msgs
media_export /opt/ros/melodic/share/media_export
message_filters /opt/ros/melodic/share/message_filters
message_generation /opt/ros/melodic/share/message_generation
message_runtime /opt/ros/melodic/share/message_runtime
mk /opt/ros/melodic/share/mk
move_base_msgs /opt/ros/melodic/share/move_base_msgs
nav_msgs /opt/ros/melodic/share/nav_msgs
nodelet /opt/ros/melodic/share/nodelet
nodelet_topic_tools /opt/ros/melodic/share/nodelet_topic_tools
nodelet_tutorial_math /opt/ros/melodic/share/nodelet_tutorial_math
octomap /opt/ros/melodic/share/octomap
octomap_msgs /opt/ros/melodic/share/octomap_msgs
orocos_kdl /opt/ros/melodic/share/orocos_kdl
pcl_conversions /opt/ros/melodic/share/pcl_conversions
pcl_msgs /opt/ros/melodic/share/pcl_msgs
pcl_ros /opt/ros/melodic/share/pcl_ros
pluginlib /opt/ros/melodic/share/pluginlib
pluginlib_tutorials /opt/ros/melodic/share/pluginlib_tutorials
polled_camera /opt/ros/melodic/share/polled_camera
position_controllers /opt/ros/melodic/share/position_controllers
python_orocos_kdl /opt/ros/melodic/share/python_orocos_kdl
python_qt_binding /opt/ros/melodic/share/python_qt_binding
qt_dotgraph /opt/ros/melodic/share/qt_dotgraph
qt_gui /opt/ros/melodic/share/qt_gui
qt_gui_cpp /opt/ros/melodic/share/qt_gui_cpp
qt_gui_py_common /opt/ros/melodic/share/qt_gui_py_common
qwt_dependency /opt/ros/melodic/share/qwt_dependency
realtime_tools /opt/ros/melodic/share/realtime_tools
resource_retriever /opt/ros/melodic/share/resource_retriever
robot_state_publisher /opt/ros/melodic/share/robot_state_publisher
ros_environment /opt/ros/melodic/share/ros_environment
rosbag /opt/ros/melodic/share/rosbag
rosbag_migration_rule /opt/ros/melodic/share/rosbag_migration_rule
rosbag_storage /opt/ros/melodic/share/rosbag_storage
rosbash /opt/ros/melodic/share/rosbash
rosboost_cfg /opt/ros/melodic/share/rosboost_cfg
rosbuild /opt/ros/melodic/share/rosbuild
rosclean /opt/ros/melodic/share/rosclean
rosconsole /opt/ros/melodic/share/rosconsole
rosconsole_bridge /opt/ros/melodic/share/rosconsole_bridge
roscpp /opt/ros/melodic/share/roscpp
roscpp_serialization /opt/ros/melodic/share/roscpp_serialization
roscpp_traits /opt/ros/melodic/share/roscpp_traits
roscpp_tutorials /opt/ros/melodic/share/roscpp_tutorials
roscreate /opt/ros/melodic/share/roscreate
rosgraph /opt/ros/melodic/share/rosgraph
rosgraph_msgs /opt/ros/melodic/share/rosgraph_msgs
roslang /opt/ros/melodic/share/roslang
roslaunch /opt/ros/melodic/share/roslaunch
roslib /opt/ros/melodic/share/roslib
roslint /opt/ros/melodic/share/roslint
roslisp /opt/ros/melodic/share/roslisp
roslz4 /opt/ros/melodic/share/roslz4
rosmake /opt/ros/melodic/share/rosmake
rosmaster /opt/ros/melodic/share/rosmaster
rosmsg /opt/ros/melodic/share/rosmsg
rosnode /opt/ros/melodic/share/rosnode
rosout /opt/ros/melodic/share/rosout
rospack /opt/ros/melodic/share/rospack
rosparam /opt/ros/melodic/share/rosparam
rospy /opt/ros/melodic/share/rospy
rospy_tutorials /opt/ros/melodic/share/rospy_tutorials
rosservice /opt/ros/melodic/share/rosservice
rostest /opt/ros/melodic/share/rostest
rostime /opt/ros/melodic/share/rostime
rostopic /opt/ros/melodic/share/rostopic
rosunit /opt/ros/melodic/share/rosunit
roswtf /opt/ros/melodic/share/roswtf
rqt_action /opt/ros/melodic/share/rqt_action
rqt_bag /opt/ros/melodic/share/rqt_bag
rqt_bag_plugins /opt/ros/melodic/share/rqt_bag_plugins
rqt_console /opt/ros/melodic/share/rqt_console
rqt_dep /opt/ros/melodic/share/rqt_dep
rqt_graph /opt/ros/melodic/share/rqt_graph
rqt_gui /opt/ros/melodic/share/rqt_gui
rqt_gui_cpp /opt/ros/melodic/share/rqt_gui_cpp
rqt_gui_py /opt/ros/melodic/share/rqt_gui_py
rqt_image_view /opt/ros/melodic/share/rqt_image_view
rqt_launch /opt/ros/melodic/share/rqt_launch
rqt_logger_level /opt/ros/melodic/share/rqt_logger_level
rqt_moveit /opt/ros/melodic/share/rqt_moveit
rqt_msg /opt/ros/melodic/share/rqt_msg
rqt_nav_view /opt/ros/melodic/share/rqt_nav_view
rqt_plot /opt/ros/melodic/share/rqt_plot
rqt_pose_view /opt/ros/melodic/share/rqt_pose_view
rqt_publisher /opt/ros/melodic/share/rqt_publisher
rqt_py_common /opt/ros/melodic/share/rqt_py_common
rqt_py_console /opt/ros/melodic/share/rqt_py_console
rqt_reconfigure /opt/ros/melodic/share/rqt_reconfigure
rqt_robot_dashboard /opt/ros/melodic/share/rqt_robot_dashboard
rqt_robot_monitor /opt/ros/melodic/share/rqt_robot_monitor
rqt_robot_steering /opt/ros/melodic/share/rqt_robot_steering
rqt_runtime_monitor /opt/ros/melodic/share/rqt_runtime_monitor
rqt_rviz /opt/ros/melodic/share/rqt_rviz
rqt_service_caller /opt/ros/melodic/share/rqt_service_caller
rqt_shell /opt/ros/melodic/share/rqt_shell
rqt_srv /opt/ros/melodic/share/rqt_srv
rqt_tf_tree /opt/ros/melodic/share/rqt_tf_tree
rqt_top /opt/ros/melodic/share/rqt_top
rqt_topic /opt/ros/melodic/share/rqt_topic
rqt_web /opt/ros/melodic/share/rqt_web
rtabmap /opt/ros/melodic/share/rtabmap
rtabmap_ros /opt/ros/melodic/share/rtabmap_ros
rviz /opt/ros/melodic/share/rviz
rviz_plugin_tutorials /opt/ros/melodic/share/rviz_plugin_tutorials
rviz_python_tutorial /opt/ros/melodic/share/rviz_python_tutorial
self_test /opt/ros/melodic/share/self_test
sensor_msgs /opt/ros/melodic/share/sensor_msgs
shape_msgs /opt/ros/melodic/share/shape_msgs
smach /opt/ros/melodic/share/smach
smach_msgs /opt/ros/melodic/share/smach_msgs
smach_ros /opt/ros/melodic/share/smach_ros
smclib /opt/ros/melodic/share/smclib
stage /opt/ros/melodic/share/stage
stage_ros /opt/ros/melodic/share/stage_ros
std_msgs /opt/ros/melodic/share/std_msgs
std_srvs /opt/ros/melodic/share/std_srvs
stereo_image_proc /opt/ros/melodic/share/stereo_image_proc
stereo_msgs /opt/ros/melodic/share/stereo_msgs
teleop_twist_keyboard /opt/ros/melodic/share/teleop_twist_keyboard
tf /opt/ros/melodic/share/tf
tf2 /opt/ros/melodic/share/tf2
tf2_eigen /opt/ros/melodic/share/tf2_eigen
tf2_geometry_msgs /opt/ros/melodic/share/tf2_geometry_msgs
tf2_kdl /opt/ros/melodic/share/tf2_kdl
tf2_msgs /opt/ros/melodic/share/tf2_msgs
tf2_py /opt/ros/melodic/share/tf2_py
tf2_ros /opt/ros/melodic/share/tf2_ros
tf_conversions /opt/ros/melodic/share/tf_conversions
theora_image_transport /opt/ros/melodic/share/theora_image_transport
topic_tools /opt/ros/melodic/share/topic_tools
trajectory_msgs /opt/ros/melodic/share/trajectory_msgs
transmission_interface /opt/ros/melodic/share/transmission_interface
turtle_actionlib /opt/ros/melodic/share/turtle_actionlib
turtle_tf /opt/ros/melodic/share/turtle_tf
turtle_tf2 /opt/ros/melodic/share/turtle_tf2
turtlesim /opt/ros/melodic/share/turtlesim
urdf /opt/ros/melodic/share/urdf
urdf_parser_plugin /opt/ros/melodic/share/urdf_parser_plugin
urdf_sim_tutorial /opt/ros/melodic/share/urdf_sim_tutorial
urdf_tutorial /opt/ros/melodic/share/urdf_tutorial
urdfdom_py /opt/ros/melodic/share/urdfdom_py
visualization_marker_tutorials /opt/ros/melodic/share/visualization_marker_tutorials
visualization_msgs /opt/ros/melodic/share/visualization_msgs
voxel_grid /opt/ros/melodic/share/voxel_grid
webkit_dependency /opt/ros/melodic/share/webkit_dependency
xacro /opt/ros/melodic/share/xacro
xmlrpcpp /opt/ros/melodic/share/xmlrpcpp

**Comment by kimsooyoung** [comment]
`rospack`으로 패키지를 확인하는 방법은 저도 사용해보지는 않았는데요, 로그를 보니 built in package들만 표시되는 것 같습니다.

그럼 요는, 여전히 
```
Error msg.
[rospack] Error: package ‘topic_tutorial’ not found
```

와 같은 에러가 발생하고 있는 상황이라는 것일까요??

**Comment by shining-sakaeru** [comment]
넵 맞습니다. 패키지 인식을 못하는게 문제인듯 하고요.

컴퓨터 환경 문제인가 싶어, 개인 컴퓨터에 다시 처음부터 셋업중입니다.
해보고 다시 피드백 드릴게요

**Comment by shining-sakaeru** [comment]
음... 개인 컴퓨터로 해도 동일한 이슈입니다.
혹시 원격으로 함께 확인 가능하신지요

**Comment by shining-sakaeru** [comment]
추가로 혹시나 해서 다른 컴퓨터 grub 환경에서도 진행했는데 동일 현상이 납니다.

**Comment by shining-sakaeru** [comment]
수정사항을 늦게 봤네요.
$ cop cpp_service_tutorial  
$ cop cpp_topic_tutorial
해당 사항을 _ws/ 폴더에서 적용하니 정상 작동합니다.

구글링을 좀 해봤는데 configuration 관련 명령어라는것뿐.. 잘 모르겠네요
해당 기능이 어떤건지만 설명 부탁드릴게요

**Comment by kimsooyoung** [comment]
[2강 노트](https://www.notion.so/2-ROS-22dcd11590bf432085273ce91e96ef9c) 중 `~/.bashrc`를 수정하는 부분이 있었습니다.

cop와 cma의 alias를 설정해주었는데요

```bash
alias cma='catkin_make -DCATKIN_WHITELIST_PACKAGES=""'
alias cop='catkin_make --only-pkg-with-deps'
```

그 의미는 다음과 같습니다.

cma : **C**atkin **M**ake **A**ll
cop : **C**atkin make **O**nly one **P**ackage

`cpp_service_tutorial` / `cpp_topic_tutorial`은 다른 패키지들과 다르게 커스텀 메세지를 사용합니다. 
그래서 개별로 사전 빌드가 필요한데요.

해당 내용은 심화 과정이어 본 강의에서는 다루지 않았습니다.
준비중인 다음 강의에서 다룰 예정이며 레퍼런스를 남기니 읽어보시면 좋을 것 같습니다.

http://wiki.ros.org/ROS/Tutorials/DefiningCustomMessages
